### ISSUE TITLE
部门嵌套问题

### ISSUE THREAD

**Issue by yoder** [huguodong/flask-permission#1]
部门编辑可以选择自己作为父级。。。然后就凉凉了

**Comment by huguodong** [comment]
没做限制，现在好了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"notifications"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月12日(星期五) 中午11:32
收件人:&nbsp;"huguodong/flask-permission"<flask-permission@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[huguodong/flask-permission] 部门嵌套问题 (#1)





 
部门编辑可以选择自己作为父级。。。然后就凉凉了
