### ISSUE TITLE
我觉得

### ISSUE THREAD

**Issue by cv936669367** [huguodong/flask-permission#2]
> 项目还行就是非登录状态可以产生数据

**Comment by huguodong** [comment]
权限校验有，为了调试方便我没加上去




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"notifications"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月17日(星期三) 中午1:54
收件人:&nbsp;"huguodong/flask-permission"<flask-permission@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[huguodong/flask-permission] 我觉得 (#2)





  
项目还行就是非登录状态可以产生数据

**Comment by cv936669367** [comment]
如果有完整的readme就好了，

**Comment by cv936669367** [comment]
是否是 login_required装饰器

**Comment by huguodong** [comment]
是的 ，看博客，有说明的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"notifications"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月17日(星期三) 下午2:14
收件人:&nbsp;"huguodong/flask-permission"<flask-permission@noreply.github.com&gt;;
抄送:&nbsp;"531035580"<531035580@QQ.COM&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [huguodong/flask-permission] 我觉得 (#2)





 
是否是 login_required装饰器
