### ISSUE TITLE
menu.py 220行代码

### ISSUE THREAD

**Issue by xueding-e** [huguodong/flask-permission#3]
这个地方的userId是不是该置None,不然210行的判断不会if user_id 永远不会走else，导致子菜单拿不出来

**Comment by huguodong** [comment]
只是一个学习项目，没怎么测试，根据需求修改



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: xuedinge <notifications@github.com&gt;
发送时间: 2020年10月9日 17:51
收件人: huguodong/flask-permission <flask-permission@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[huguodong/flask-permission] menu.py 220行代码 (#3)
