### ISSUE TITLE
预览地址失效

### ISSUE THREAD

**Issue by obrua** [huguodong/flask-permission#4]

**Comment by huguodong** [comment]
阿里云到期了。。。。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huguodong/flask-permission"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月23日(星期五) 下午3:25
收件人:&nbsp;"huguodong/flask-permission"<flask-permission@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[huguodong/flask-permission] 预览地址失效 (#4)
