### ISSUE TITLE
数据库表能导出一份吗~

### ISSUE THREAD

**Issue by obrua** [huguodong/flask-permission#5]

**Comment by obrua** [comment]
能提供一份吗~SQL

**Comment by huguodong** [comment]
有数据库建表语句啊，https://www.cnblogs.com/huguodong/p/12433643.html




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huguodong/flask-permission"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月30日(星期五) 下午4:04
收件人:&nbsp;"huguodong/flask-permission"<flask-permission@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [huguodong/flask-permission] 数据库表能导出一份吗~ (#5)





 
造数据太耗时了
